@hostname = localhost
@port = 8300
@host = {{hostname}}:{{port}}
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5LCJ0eXBlIjoiYWNjZXNzIiwianRpIjoiOWY3MzA2ZDMtZDA5NS00NTYxLWFlM2MtMjgzOWU4MWE5YzEyIiwiaWF0IjoxNzg1MDc1MjA4LCJleHAiOjE3ODUxNjE2MDgsImlzcyI6Im5lb2Nyb3duIn0.1aV1iT2Uzb5xEXntc4r96rJQcrrOcMD82UaXpfOmJ40


### crawl v2ex/hot-top10
post http://{{host}}/api/crawler/v2ex/hot-top10/crawl
Authorization: Bearer {{token}}


### crawl v2ex/hot-top10 and send mail
post http://{{host}}/api/crawler/v2ex/hot-top10/crawl-and-send-mail
Authorization: Bearer {{token}}


### get v2ex/hot-top10 result
get http://{{host}}/api/crawler/v2ex/hot-top10/result
Authorization: Bearer {{token}}
