process.env.POSTAL_SMTP_SERVER ??= 'smtp.example.com'
process.env.POSTAL_SMTP_PORT ??= '465'
process.env.POSTAL_FROM_EMAIL ??= 'no-reply@example.com'
process.env.POSTAL_FROM_PASS ??= 'test-smtp-password'
process.env.POSTAL_FROM_NAME ??= 'NeoCrown Test'
process.env.EMAIL_VERIFICATION_SECRET ??=
  'test-verification-secret-at-least-32-characters'
process.env.V2EX_HOT_TOP10_MAIL_TO ??= 'receiver@example.com'
process.env.JWT_SECRET ??= 'test-jwt-secret'
process.env.JWT_ACCESS_EXPIRE ??= '10m'
process.env.JWT_REFRESH_EXPIRE ??= '7d'
process.env.JWT_ISSUER ??= 'neocrown-test'
process.env.ATTACH_VIEW_BASE_URL ??= 'http://localhost:8300/public/uploads'
process.env.ATTACH_UPLOAD_DIR_PATH ??= './public/uploads'
process.env.ATTACH_VIEW_LARGE_FILE_BASE_URL ??=
  'http://localhost:8300/public/larges'
process.env.ATTACH_UPLOAD_LARGE_FILE_PATH ??= './public/larges'
process.env.ATTACH_CHUNK_DIR_PATH ??= './public/chunks'
process.env.ATTACH_CHUNK_DIR_SALT ??= 'neocrown-test-chunk-salt'
